### ISSUE TITLE
[Bug] When removing a song from the queue the queue becomes an 'endless' grey screen

### ISSUE THREAD

**Issue by bambadon** [UnicornsOnLSD/finamp#79] opened 2021-07-18 10:19 UTC
Expected behavior: when you open up the queue and scroll to the bottom of it, the view will 'bounce' and stop you from scrolling further down. You can remove songs from this queue by swiping them to the left. 

However on certain queues (I think long ones, I can't replicate it on smaller queues i.e. if I only play an album with a limited number of tracks and those compose of the queue) if you remove a few songs from the queue and scroll all the way down there's a grey zone below the queue. You can keep scrolling forever.

Tested on iPadOS.

**Comment by UnicornsOnLSD** [comment] 2021-07-18 10:27
Could you send your main thread logs when this happens? I'm pretty sure I know what the issue is. If you don't want to send all of your logs (next update will hide the base URL), just long press on the latest error log, it should say something about an index.

**Comment by bambadon** [comment] 2021-07-18 10:40
This is the latest error after triggering this bug:

[Flutter/SEVERE] 2021-07-18 12:31:49.381413: RangeError (index): Invalid value: Not in inclusive range 0..100: 101

#0      _GrowableList.[] (dart:core-patch/growable_array.dart:254)
#1      _QueueListState.build.<anonymous closure>.<anonymous closure> (package:finamp/components/PlayerScreen/QueueList.dart:35)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:455)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1213)
#4      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1226)
#5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535)
#6      SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1219)
#7      RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
#8      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1889)
#9      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:912)
#10     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1889)
#11     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
#12     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484)
#13     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239)
#14     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1779)
#16     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137)
#17     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1779)
#19     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510)
#20     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574)
#21     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483)
#22     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1636)
#23     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881)
#24     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462)
#25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876)
#26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328)
#27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
#28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
#29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998)
#30     _rootRun (dart:async/zone.dart:1354)
#31     _CustomZone.run (dart:async/zone.dart:1258)
#32     _CustomZone.runGuarded (dart:async/zone.dart:1162)
#33     _invoke (dart:ui/hooks.dart:163)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259)
#35     _drawFrame (dart:ui/hooks.dart:126)

**Comment by UnicornsOnLSD** [comment] 2021-08-06 18:36
Fixed in c8f7672

**Closed by UnicornsOnLSD** 2021-08-06 18:36 UTC
