### ISSUE TITLE
[Feature Request] Transcoding on cellular network

### ISSUE THREAD

**Issue by Maxplosion** [UnicornsOnLSD/finamp#168] opened 2021-12-28 22:11 UTC
Hi, have not found a similar feature request yet so here is this one.
could you maybe add a toggle to allow transcoding only while on cellular network? so its possible to listen lossless on home wifi but have transcoding on the go.
but please keep the current always transcode toggle, its really useful!

**Comment by UnicornsOnLSD** [comment] 2021-12-29 00:49
Duplicate of #44

**Closed by UnicornsOnLSD** 2021-12-29 00:49 UTC
