### ISSUE TITLE
Feature Request: resume failed downloads

### ISSUE THREAD

**Issue by k1llerk3ks** [UnicornsOnLSD/finamp#266] opened 2022-07-07 13:38 UTC
When downloads fail, one can watch them on the top right at the red Exclamation mark. I am missing the function to retry a failed download, e.g. by just clicking on the failed item.

**Comment by UnicornsOnLSD** [comment] 2022-07-14 21:45
Duplicate of #214

**Closed by UnicornsOnLSD** 2022-07-14 21:45 UTC
