### ISSUE TITLE
Add Button to downolad whole Library

### ISSUE THREAD

**Issue by metalune1** [UnicornsOnLSD/finamp#227] opened 2022-05-05 21:18 UTC
I'd love to use this App as my only Music App but for that I'd need to have the ability to quickly download my entire library, not even transcoded as they're all in a perfect format already and I have plenty of space on my phone. I'd implement it myself but I'm not too well-versed in Mobile Dev.

**Comment by UnicornsOnLSD** [comment] 2022-06-08 17:21
Duplicate of #34

**Closed by UnicornsOnLSD** 2022-06-08 17:21 UTC
