### ISSUE TITLE
Remove favorites icon in views in which it is currently broken

### ISSUE THREAD

**Issue by foss-** [UnicornsOnLSD/finamp#176] opened 2022-01-12 20:42 UTC
For some views favorites is broken. For those (maybe temporary until fixed) the icon could be removed.

**Comment by UnicornsOnLSD** [comment] 2022-01-12 21:03
Duplicate of #72 (don't blame you for making a new issue, I really should have fixed this by now lol)

**Closed** 2022-01-12 21:03 UTC
