### ISSUE TITLE
[Feature-Request] Shuffle Button on Album Screen

### ISSUE THREAD

**Issue by Vodes** [UnicornsOnLSD/finamp#27] opened 2021-04-22 11:16 UTC
Its just more convenient to have a shuffle button on the Album Screen

Maybe in the title bar, like how Gelli/Phonograph does it

**Comment by UnicornsOnLSD** [comment] 2021-04-22 11:26
Duplicate of #23

**Closed by UnicornsOnLSD** 2021-04-22 11:26 UTC
