### ISSUE TITLE
[Enhancement] Set default download location

### ISSUE THREAD

**Issue by velamvela** [UnicornsOnLSD/finamp#88] opened 2021-07-22 01:50 UTC
Do not require confirmation of where to store downloads, instead have files stored in the default location in settings

Remove the "add downloads" popup when clicking on downloads

**Comment by UnicornsOnLSD** [comment] 2021-07-22 02:21
Sort of duplicate of #82 and #65. What I'm probably going to do is make it so that the dialog doesn't show when there is only one download location.

**Closed by UnicornsOnLSD** 2021-07-22 02:21 UTC
