### ISSUE TITLE
Play controls fail to render and show a grey square

### ISSUE THREAD

**Issue by drazil100** [UnicornsOnLSD/finamp#288] opened 2022-07-25 22:41 UTC
Issue persists after closing the app and reopening it but only for a specific one of my albums. (Could be others but this is all I have found so far)
 
![image](https://user-images.githubusercontent.com/17794391/180885960-52c0328e-05dd-4f1c-91e0-e2308580b1ed.png)

This is the error I get. 
```
[Flutter/SEVERE] 2022-07-25 17:35:16.624386: RangeError (length): Invalid value: Valid value range is empty: -1

#0      SongName.build.<anonymous closure> (package:finamp/components/PlayerScreen/SongName.dart)
#1      StreamBuilder.build (package:flutter/src/widgets/async.dart:442)
#2      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:124)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
#13     _rootRun (dart:async/zone.dart:1426)
#14     _CustomZone.run (dart:async/zone.dart:1328)
#15     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#16     _invoke (dart:ui/hooks.dart:151)
#17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#18     _drawFrame (dart:ui/hooks.dart:115)
```

**Comment by UnicornsOnLSD** [comment] 2022-07-25 22:46
Duplicate of #278, will make a release with the fix in tomorrow

**Closed by UnicornsOnLSD** 2022-07-25 22:46 UTC
