### ISSUE TITLE
[Feature Request] Add another option to filter by

### ISSUE THREAD

**Issue by manf0001** [UnicornsOnLSD/finamp#51] opened 2021-05-30 14:31 UTC
Hi,  I just came across this app and already I love it just for the simple fact the ability for offline play.  Could you please add the ability to filter songs via Genres?

Thanks.

**Comment by UnicornsOnLSD** [comment] 2021-05-30 16:02
Duplicate of #30

**Closed by UnicornsOnLSD** 2021-05-30 16:02 UTC
