### ISSUE TITLE
Getting HandshakeExcetion: WRONG_VERSION_NUMBER on Android 11

### ISSUE THREAD

**Issue by domportera** [UnicornsOnLSD/finamp#58] opened 2021-07-03 20:03 UTC
I'm trying to use Finamp on Android 11 using my Pixel 2 and am getting the following error:

![Screenshot_20210703-160147](https://user-images.githubusercontent.com/6530600/124365774-226fa500-dc18-11eb-8c01-f4c01e9c9826.png)

Any idea what the problem might be or if I could solve it on my end? I'd love to use this player. Thanks!

**Comment by UnicornsOnLSD** [comment] 2021-07-03 20:05
Duplicate of #57

**Comment by domportera** [comment] 2021-07-03 20:06
oops sorry! I promise I did a search beforehand lmao

**Closed by UnicornsOnLSD** 2021-07-03 20:05 UTC
