### ISSUE TITLE
logout fails, can't switch host values

### ISSUE THREAD

**Issue by ddevler** [UnicornsOnLSD/finamp#205] opened 2022-03-29 02:20 UTC
Switched servers and can't logout in the app to switch the host or IP. The old server is offline. Pressing logout throws and error since can't connect to the server.  Due to the error the logout fails and won't clear existing information. This means I can't update the host value. I had to delete the app and reinstall to switch hosts.

**Comment by UnicornsOnLSD** [comment] 2022-03-29 05:53
Duplicate of #169 (there's literally one last small thing I need to do before 0.6.0, then I'll be able to release it :) )

**Closed by UnicornsOnLSD** 2022-03-29 05:53 UTC
