### ISSUE TITLE
[Feature Request] add alphabet scrolling to right side of view were useful

### ISSUE THREAD

**Issue by foss-** [UnicornsOnLSD/finamp#174] opened 2022-01-10 23:33 UTC
**Currently**
Scrolling to artist in middle of alphabet can take a long time for large libraries.

**Expected**
Adding an alphabet to the right side of the screen allowing to instantly scroll to the target letter would make the interaction much quicker and simple.

Some inspiration by Plex:
<img width="414" alt="plex" src="https://user-images.githubusercontent.com/5708172/148855126-0de601a6-5316-4708-987f-67f3b67df20f.png">

**Comment by UnicornsOnLSD** [comment] 2022-01-10 23:42
Duplicate of #125

**Closed** 2022-01-10 23:42 UTC
