### ISSUE TITLE
NoSuchMethod Error

### ISSUE THREAD

**Issue by nathancoooper** [UnicornsOnLSD/finamp#206] opened 2022-04-02 11:21 UTC
When I open the Finamp app I receive this:
![image](https://user-images.githubusercontent.com/100081814/161380836-c5a01748-a423-4662-af12-8ceb0df65d43.png)

The logs state:
![image](https://user-images.githubusercontent.com/100081814/161380841-b4dcd068-39ee-49a1-86f8-502c298b834f.png)

**Comment by nathancoooper** [comment] 2022-04-02 11:31
(platform: iOS 15.0.2 - iPhone SE Gen. 2)

**Comment by UnicornsOnLSD** [comment] 2022-04-04 21:16
Duplicate of #72

**Closed** 2022-04-04 21:17 UTC
