### ISSUE TITLE
[Feature Request] Show quality of current song playing / songs in library

### ISSUE THREAD

**Issue by GreenCobalt** [UnicornsOnLSD/finamp#260] opened 2022-07-04 20:40 UTC
Similar to Plexamp's version of this - just show like "MP3 320kbps" or "FLAC 44.1/24". 
Shown under the Now Playing screen, maybe where it says "Streaming \n Direct", change it to "Direct \n *quality*"?

Also at the bottom of albums it'd be nice to have just a little badge showing this.

**Comment by UnicornsOnLSD** [comment] 2022-07-04 20:42
Duplicate of #211

**Closed by UnicornsOnLSD** 2022-07-04 20:42 UTC
