### ISSUE TITLE
Desktop Client

### ISSUE THREAD

**Issue by trymeouteh** [UnicornsOnLSD/finamp#242] opened 2022-05-28 20:22 UTC
With the app being made with flutter, please release it on Windows, Mac and Linux.

I would suggest releasing it into the AUR and Pacstall on Linux to cover most distros.

**Comment by UnicornsOnLSD** [comment] 2022-05-28 20:29
Duplicate of #40 (will post an update in there)

**Closed by UnicornsOnLSD** 2022-05-28 20:29 UTC
