### ISSUE TITLE
[Feature Request] Android Auto support

### ISSUE THREAD

**Issue by sixsixfive** [UnicornsOnLSD/finamp#173] opened 2022-01-10 07:13 UTC
It would be nice to have Android Auto support, since the official client does not support transcoding by bitrate.

**Comment by UnicornsOnLSD** [comment] 2022-01-10 23:44
Sort of duplicate of #24, support for both Android Auto and CarPlay will likely come as one patch

**Closed by UnicornsOnLSD** 2022-01-10 23:44 UTC
