### ISSUE TITLE
Feature Request: last.fm Scrobbling

### ISSUE THREAD

**Issue by mattipunkt** [UnicornsOnLSD/finamp#191] opened 2022-02-17 08:29 UTC
When listening over FinAmp, there are no last.fm-Scrobbles, even if there is the last.fm-Plugin installed in Jellyfin. A last.fm-support would be really helpful.

**Comment by UnicornsOnLSD** [comment] 2022-02-21 14:53
Duplicate of #87

**Closed by UnicornsOnLSD** 2022-02-21 14:53 UTC
