### ISSUE TITLE
[Feature] Show streaming/transcoding info

### ISSUE THREAD

**Issue by florinsdistortedvision** [UnicornsOnLSD/finamp#298] opened 2022-08-05 10:43 UTC
Right now, Finamp shows nicely STREAMING DIRECT or TRANSCODING which works out well, however it would be nice to be able to tap on it and show more info similar to [Roon ](http://thehbproject.com/files/img/fotos/testen/RoonLabs/Roonlabs02.jpg) (bit of a blurry pic but you get the gist). Basically basic stuff such as audio format (FLAC, ALAC etc), bitrate (in kbps), sample rate (kHz), bit depth (16bit, 24bit etc).

**Comment by UnicornsOnLSD** [comment] 2022-08-15 22:39
Duplicate of #184

**Closed by UnicornsOnLSD** 2022-08-15 22:39 UTC
