### ISSUE TITLE
Exclude downloaded songs from iCloud backup

### ISSUE THREAD

**Issue by robthr** [UnicornsOnLSD/finamp#135] opened 2021-10-06 00:03 UTC
After downloading playlists to my phone a few weeks ago, I found that iCloud backup does not exclude the downloaded music from the backups. Is there any way to do this automatically? In the meantime I have disabled the entire app's backups.
![IMG_1533](https://user-images.githubusercontent.com/34327237/136119989-5dcd865a-2d36-4894-ab5b-47a1d863b6eb.jpg)

**Comment by UnicornsOnLSD** [comment] 2021-10-06 00:22
Duplicate of #118

**Closed by UnicornsOnLSD** 2021-10-06 00:22 UTC
