### ISSUE TITLE
[Bug] shuffle all songs less then count

### ISSUE THREAD

**Issue by stormbyte** [UnicornsOnLSD/finamp#119] opened 2021-08-30 14:26 UTC
When using the shuffle all songs button with the default 250 count and having 199 songs downloaded.
Being in offline mode results in an error `not in inclusive range 0..199: 250`

**Comment by UnicornsOnLSD** [comment] 2021-08-30 14:47
Duplicate of #117

**Closed by UnicornsOnLSD** 2021-08-30 14:47 UTC
