### ISSUE TITLE
[Feature] Track Progress/Played For Podcasts/Books

### ISSUE THREAD

**Issue by seniorm0ment** [UnicornsOnLSD/finamp#195] opened 2022-02-22 12:36 UTC
Would be appreciated to have the ability to track progress for specific libraries.
For example, if I have a "Music" library with podcasts (with the ability to disable for my actual music library), or ebooks, it would be nice to be able to remember what tracks I've listened to, and where I am in the track.

This seems to be something jellyfin itself currently lacks (proper support for podcasts and audiobooks), but I figured maybe something could be done client side for the time being to make the app more usable for audiobooks and podcasts.

**Comment by UnicornsOnLSD** [comment] 2022-02-23 13:13
Sort of duplicate of #60, although I'll make sure I let the option be set per-library :)

**Closed by UnicornsOnLSD** 2022-02-23 13:13 UTC
