### ISSUE TITLE
[Feature Request] Publish app to TestFlight

### ISSUE THREAD

**Issue by sambhavsaggi** [UnicornsOnLSD/finamp#29] opened 2021-04-30 23:05 UTC
If you publish the app to TestFlight and make it a public app, you can get more testers and people who don't want to go through using Xcode can use this.

**Comment by UnicornsOnLSD** [comment] 2021-05-01 00:10
I'd love to publish on TestFlight (and eventually the App Store), but Apple doesn't let you do much without a developer license. All I can do is run the app on either a simulator, or a device connected over USB. I can't even create an IPA.

I should be able to get an Apple developer license (and Google Play) in a few months, so unless you have access to a Mac, there's currently no way to run Finamp on iOS.

**Comment by AD-Wright** [comment] 2021-05-01 00:16
Are you interested in creating some way to sponsor Finamp development costs like the yearly Apple Developer fee?  Given the 84 stars on this repository, I imagine some people would be willing to donate a small amount yearly to support this program, but I don't know how you would feel about that (it can feel different coding for something other people are paying for, rather than something you are paying for as a passion project).  I know we all appreciate the time you have put into the project so far.

**Comment by UnicornsOnLSD** [comment] 2021-05-01 00:21
@AD-Wright It's not a financial issue, and I said in [this Reddit comment](https://www.reddit.com/r/jellyfin/comments/n1fdtg/finamp_040_custom_download_locations_playshuffle/gwfavab/) that I don't want to take donations for this project since it doesn't cost me anything (Apple/Google fees are pretty negligible). I can't release on the App Store/Play Store right now because I won't be elligible for a few months.

**Comment by nickzana** [comment] 2021-05-01 17:37
I have an Apple developer subscription and would be happy to post to TestFlight (or App Store, if desired) at least until @UnicornsOnLSD can get a developer account. I will probably go ahead and do it just for myself + friends anyways and can post a public link.

**Comment by UnicornsOnLSD** [comment] 2021-05-01 18:27
@nickzana I'll be happy for you to publish to TestFlight, but I'd personally like to publish the App Store version myself. I could send you bundles if you don't want to compile the project yourself :)

I'll also add it to the README if you make a public TestFlight link.

**Comment by nickzana** [comment] 2021-05-01 20:55
Ok, sounds good. I'll let you know when it's on TestFlight.

Has it been tested on iOS? I got it running in the simulator, however I'm struggling to get a music library to show up in the app (with both @sambhavsaggi's and my own library). Farthest I've gotten is getting it to show artists, but no albums or songs. Library works as expected on web.

Could be a Jellyfin configuration issue on my side. I'll upload to TestFlight and once it's approved, maybe others with known working music libraries can test it.

**Comment by UnicornsOnLSD** [comment] 2021-05-01 21:28
I've tested it on iOS and it worked on my simulator/iPhone 6. I don't think I did anything breaking, but I'll test with my server later.

**Comment by luke2m** [comment] 2021-05-03 01:03
> once it's approved, maybe others with known working music libraries can test it.

I’d be happy to test when you get TestFlight set up.

**Comment by luke2m** [comment] 2021-05-17 00:48
@nickzana any update?

**Comment by anthonylavado** [comment] 2021-05-18 08:13
Working on this now actually.

**Comment by anthonylavado** [comment] 2021-05-19 02:56
Lots of review errors for permission reasons on App Store Connect. Gonna dig deeper.

**Comment by UnicornsOnLSD** [comment] 2021-05-19 10:20
@anthonylavado Could you send those errors? I might be able to look into it too.

**Comment by UnicornsOnLSD** [comment] 2021-05-26 20:00
@nickzana @anthonylavado Just pushed some new commits that should fix the build and verification errors on iOS. Mostly related to build targets and the permission package.

**Comment by cfredericksen** [comment] 2021-06-10 12:56
I’d be happy to test when you get TestFlight set up.

**Comment by UnicornsOnLSD** [comment] 2021-06-10 15:59
I'll be able to enrol in the Apple Developer Program in July, so I should be able to properly release Finamp on the App Store soon.

**Comment by UnicornsOnLSD** [comment] 2021-07-02 21:25
![Screenshot 2021-07-02 at 22 24 47](https://user-images.githubusercontent.com/44349936/124329953-5bf6d080-db84-11eb-8309-ddd69b471f03.png)
Submitted for review. When 0.5 is ready, it will be released on the App Store/Play Store :)

**Comment by UnicornsOnLSD** [comment] 2021-07-09 02:19
Just got accepted (after lots of rejections due to copyright), 0.5 will be released on the App Store :D

**Comment by drazil100** [comment] 2021-07-09 02:21
Hell yeah! Looking forward to it!

**Comment by sambhavsaggi** [comment] 2021-07-09 03:57
Any ETA on either the Testflight link or 0.5.0 release?

**Comment by UnicornsOnLSD** [comment] 2021-07-09 04:07
I'll probably do sorting (#46) and multiple users/libraries. Once that's done, I'd say that's enough for 0.5. I could probably get those two things done tomorrow or in a few days. There'll be a delay caused by adding a new version to the App Store, but that should hopefully be fine now.

**Comment by UnicornsOnLSD** [comment] 2021-07-11 15:33
0.5.0 is now released on the App Store :D

**Closed by UnicornsOnLSD** 2021-07-11 15:33 UTC

**Comment by drazil100** [comment] 2021-07-11 17:44
Great job this app is fantastic! I have been using jellyfin since one of it's earliest versions and until now I haven't really been able to use it as my primary music client due to a variety of issues. I have used other apps (foobar2000) but syncing music was a pain and it stopped working several months ago. 

I am really looking forward to the future of finamp and wanted to say thank you for making this 😀

**Comment by Chaphasilor** [comment] 2024-02-21 11:39
Sure, but we can only give you the invite once there actually **is** a TestFlight beta ^^  
Give us a few more days please, we're working on it!
