### ISSUE TITLE
No sound at all on Fiio DX200

### ISSUE THREAD

**Issue by vincegre** [UnicornsOnLSD/finamp#128] opened 2021-09-12 10:14 UTC
Hi

I'm using a Fiio DX200 divec that is a Hifi walkman running on Android 8.1.0. I have been using other music apps such as Plex or Plexamp to listen my FLAC library without any issues. When running Finamp (installed from Fdroid), it works fine but I get absolutely no sound coming up. My music library is only FLAC files and I have no problem to listen them from Jellyfin web interface or dedicated app so I know files are good on server !
How can I help debug that problem ?

Thanks for that nice app ;)

Vincèn

**Comment by UnicornsOnLSD** [comment] 2021-09-12 17:52
This is kind of like #22, could you send your logs? I feel like this is a weird Android issue.

**Comment by vincegre** [comment] 2021-09-12 17:57
oups yep didn't find that ticket before opening that one ! will continue on other ;)

**Comment by UnicornsOnLSD** [comment] 2021-09-14 14:39
Duplicate of #22

**Closed by UnicornsOnLSD** 2021-09-14 14:39 UTC
